### ISSUE TITLE
abundance plot error

### ISSUE THREAD

**Issue by ajinkyakhilari** [genomicsITER/NanoCLUST#10]
[22/e6402c] process > QC (1)                        [100%] 1 of 1 ✔
[64/24fe3f] process > fastqc (1)                    [100%] 1 of 1 ✔
[c0/ad2b7c] process > kmer_freqs (1)                [100%] 1 of 1 ✔
[f2/0a2839] process > read_clustering (1)           [100%] 1 of 1 ✔
[f7/cadd4e] process > split_by_cluster (1)          [100%] 1 of 1 ✔
[25/d2be15] process > read_correction (17)          [100%] 17 of 17 ✔
[3a/1f7328] process > draft_selection (17)          [100%] 17 of 17 ✔
[bc/056b51] process > racon_pass (17)               [100%] 17 of 17 ✔
[aa/ca1f63] process > medaka_pass (17)              [100%] 17 of 17 ✔
[35/61343c] process > consensus_classification (17) [100%] 17 of 17 ✔
[b1/6f6045] process > join_results (1)              [100%] 1 of 1 ✔
[00/9e1975] process > get_abundances (1)            [100%] 1 of 1, failed: 1 ✘
[-        ] process > plot_abundances               -
[a1/a41915] process > output_documentation          [100%] 1 of 1 ✔
Execution cancelled -- Finishing pending tasks before exit
[0;35m[nf-core/nanoclust] Pipeline completed with errors
Error executing process > 'get_abundances (1)'

Caused by:
  Process `get_abundances (1)` terminated with an error exit status (1)

Command executed [/NanoporeTools/NanoCLUST/templates/get_abundance.py]:

  #!/usr/bin/env python
  
  import numpy as np
  import matplotlib.pyplot as plt
  from matplotlib import rc
  import pandas as pd
  from functools import reduce
  import requests
  import json
  #https://unipept.ugent.be/apidocs/taxonomy
  
  def get_taxname(tax_id,tax_level):
      tags = {"S": "species_name","G": "genus_name","F": "family_name","O":'order_name', "C": "class_name"}
      tax_level_tag = tags[tax_level]
      
      path = 'http://api.unipept.ugent.be/api/v1/taxonomy.json?input[]=' + str(int(tax_id)) + '&extra=true&names=true'
      complete_tax = requests.get(path).text
      return json.loads(complete_tax)[0][tax_level_tag]
  
  def get_abundance_values(names,paths):
      dfs = []
      for name,path in zip(names,paths):
          data = pd.read_csv(path, index_col=False, sep=';').iloc[:,1:]
  
          total = sum(data['reads_in_cluster'])
          rel_abundance=[]
  
          for index,row in data.iterrows():
              rel_abundance.append(row['reads_in_cluster'] / total)
              
          data['rel_abundance'] = rel_abundance
          dfs.append(pd.DataFrame({'taxid': data['taxid'], 'rel_abundance': rel_abundance}))
          data.to_csv("" + name + "_nanoclust_out.txt")
  
      return dfs
  
  def merge_abundance(dfs,tax_level):
      df_final = reduce(lambda left,right: pd.merge(left,right,on='taxid',how='outer').fillna(0), dfs)
      df_final["taxid"] = [get_taxname(row["taxid"], tax_level) for index, row in df_final.iterrows()]
      df_final_grp = df_final.groupby(["taxid"], as_index=False).sum()
      return df_final_grp
  
  def get_abundance(names,paths,tax_level):
      if(not isinstance(paths, list)):
          paths = [paths]
          names = [names]
  
      dfs = get_abundance_values(names,paths)
      df_final_grp = merge_abundance(dfs, tax_level)
      df_final_grp.to_csv("rel_abundance_"+ names[0] + "_" + tax_level + ".csv", index = False)
  
  paths = "barcode10_chimfilt.nanoclust_out.txt"
  names = "barcode10_chimfilt"
  
  get_abundance(names,paths, "G")
  get_abundance(names,paths, "S")
  get_abundance(names,paths, "O")
  get_abundance(names,paths, "F")

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File ".command.sh", line 55, in <module>
      get_abundance(names,paths, "G")
    File ".command.sh", line 49, in get_abundance
      df_final_grp = merge_abundance(dfs, tax_level)
    File ".command.sh", line 39, in merge_abundance
      df_final["taxid"] = [get_taxname(row["taxid"], tax_level) for index, row in df_final.iterrows()]
    File ".command.sh", line 39, in <listcomp>
      df_final["taxid"] = [get_taxname(row["taxid"], tax_level) for index, row in df_final.iterrows()]
    File ".command.sh", line 16, in get_taxname
      path = 'http://api.unipept.ugent.be/api/v1/taxonomy.json?input[]=' + str(int(tax_id)) + '&extra=true&names=true'
  ValueError: cannot convert float NaN to integer

Work dir:
  /NanoporeTools/NanoCLUST/work/00/9e19751bb522057d633880bce32a6a

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

(base) bash-4.2$

**Comment by ajinkyakhilari** [comment]
hello can anybody help

**Comment by genomicsITER** [comment]
Hi,

It seems that some classification results are causing trouble. You can check the output file "sample.nanoclust_out.txt". There is a column named "taxid" which refers to NCBI taxonomic ID. Are the columns values valid (integer) for all values? It would be nice to have the command you used to run the pipeline and set database parameters.
