### ISSUE TITLE
Phylum level

### ISSUE THREAD

**Issue by aldertzomer** [genomicsITER/NanoCLUST#16]
I noticed in the test output that there is no phylum level output file. Is that not supported? I couldn't find an option for it. 
thanks :)

**Comment by genomicsITER** [comment]
Hi,

Thank you for opening this issue. We have committed some changes into the repository which include the phylum and class level output files in the get_abundance step. At this time, the pipeline generates output files for all taxonomic levels. This is something that we would like to change in the future and let the users control the taxonomic level of outputs.

Regards,

Héctor
