### ISSUE TITLE
pipeline error

### ISSUE THREAD

**Issue by ajinkyakhilari** [genomicsITER/NanoCLUST#17]
executor >  local (5)
[b6/f83e29] process > demultiplex_porechop (1) [100%] 1 of 1, cached: 1 ✔
[46/63d408] process > QC (2)                   [100%] 12 of 12, cached: 12 ✔
[a2/a381f3] process > fastqc (8)               [100%] 12 of 12, cached: 12 ✔
[7b/f93ed0] process > kmer_freqs (7)           [100%] 12 of 12, cached: 12 ✔
[b4/723722] process > read_clustering (5)      [100%] 11 of 11, cached: 9
[01/ed4cdd] process > split_by_cluster (3)     [ 89%] 8 of 9, cached: 6, failed: 2
[-        ] process > read_correction          [  0%] 0 of 70
[-        ] process > draft_selection          -
[-        ] process > racon_pass               -
[-        ] process > medaka_pass              -
[-        ] process > consensus_classification -
[-        ] process > join_results             -
[-        ] process > get_abundances           -
[-        ] process > plot_abundances          -
[d6/8e92ba] process > output_documentation     [100%] 1 of 1, cached: 1 ✔
Error executing process > 'split_by_cluster (9)'

Caused by:
  Missing output file(s) `*[0-9]*.log` expected by process `split_by_cluster (9)`

Command executed:

  sed 's/\srunid.*//g' BC07_qced_reads_set.fastq > only_id_header_readfile.fastq
  CLUSTERS_CNT=$(awk '($5 ~ /[0-9]/) {print $5}' hdbscan.output.tsv | sort -nr | uniq | head -n1)

  for ((i = 0 ; i <= $CLUSTERS_CNT ; i++));
  do
     cluster_id=$i
     awk -v cluster="$cluster_id" '($5 == cluster) {print $1}' hdbscan.output.tsv > $cluster_id\_ids.txt
     seqtk subseq only_id_header_readfile.fastq $cluster_id\_ids.txt > $cluster_id.fastq
     READ_COUNT=$(( $(awk '{print $1/4}' <(wc -l $cluster_id.fastq)) ))
     echo -n "$cluster_id;$READ_COUNT" > $cluster_id.log
  done

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /home/administrator/Desktop/Bovine_Mastitis_Project/Mastitis_nanopore_data/Project_1/Project1/Project1/20190612_1214_MN26935_FAK72557_229de4aa/work/ba/711a8ad94186576f7e4db76c222be8

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz

**Comment by genomicsITER** [comment]
HI, thank you for opening this issue

It seems that some of your samples doesn't contain enough reads to call any cluster (probably a negative control o failed sample?). Since you are demultiplexing before anything else, we would recommend to isolate that demultiplexing step and run it before the pipeline with a standalone tool. Then you could individually select the barcodes that are eligible for the NanoCLUST method (we have been testing it with a minimum of 80k-100k per barcode).
