### ISSUE TITLE
Installation of NanoCLUST

### ISSUE THREAD

**Issue by gghyl** [genomicsITER/NanoCLUST#25]
Hi,

I would like to install NanoCLUST, but I am not sure how to install it as I cannot find the command for installation of NanoCLUST from either Github or Conda. I have installed the Nextflow and conda in my desktop. What should I do next to install NanoCLUST? Thank you.

**Comment by genomicsITER** [comment]
Hi, 

Thank you for opening the issue. Installation and usage is specified in README.md and /docs.

Before getting NanoCLUST:

- Install conda/docker (Miniconda 3 recommended)
- Install nextflow (Quick Start section from https://www.nextflow.io/). Java is required for Nextflow
- Clone the repository with the `git clone` command as usual

There is no need to install anything else. Nextflow software run the pipeline from the files you have already cloned
