### ISSUE TITLE
BLAST Database error: No alias or index file found for nucleotide database

### ISSUE THREAD

**Issue by fahadkhokhar** [genomicsITER/NanoCLUST#3]
Hello,

I have followed the instructions to download the required databases, but this problems still persists:

Command executed:

  export BLASTDB=
  export BLASTDB=$BLASTDB:/home/ubuntu/bin/NanoCLUST/db/taxdb
  blastn -query consensus.fasta -db /home/ubuntu/bin/NanoCLUST/db/16S_ribosomal_RNA -task blastn -dust no -outfmt "10 sscinames staxids evalue length pident" -evalue 11 -max_hsps 50 -max_target_seqs 5 | sed 's/,/;/g' > consensus_classification.csv
  #DECIDE FINAL CLASSIFFICATION
  cat 11_draft.log > 11_blast.log
  echo -n ";" >> 11_blast.log
  BLAST_OUT=$(cut -d";" -f1,2,4,5 consensus_classification.csv | head -n1)
  echo $BLAST_OUT >> 11_blast.log

Command exit status:
  2

Command output:
  (empty)

Command error:
  BLAST Database error: No alias or index file found for nucleotide database [/home/ubuntu/bin/NanoCLUST/db/16S_ribosomal_RNA] in search path [/media/kraken/NanoCLUST/work/ff/483a7d41cb9ec59d392dda702d6293::/home/ubuntu/bin/NanoCLUST/db/taxdb:]

Work dir:
  /media/kraken/NanoCLUST/work/ff/483a7d41cb9ec59d392dda702d6293

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by HaiyangDu** [comment]
> 你好，
> 
> 我已经按照说明下载了所需的数据库，但是此问题仍然存在：
> 
> 命令执行：
> 
> 导出BLASTDB =
> 导出BLASTDB = $ BLASTDB：/ home / ubuntu / bin / NanoCLUST / db / taxdb blastn-
> 查询共识。fasta-db / home / ubuntu / bin / NanoCLUST / db / 16S_ribosomal_RNA -task blastn -dust no -outfmt“ 10个sscinames staxids evalue长度pident“ -evalue 11 -max_hsps 50 -max_target_seqs 5 | sed's /，/; / g'>共识
> _分类.csv #DECIDE最终分类
> cat 11_draft.log> 11_blast.log
> echo -n“;” >> 11_blast.log
> BLAST_OUT = $（cut -d“;” -f1,2,4,5confidence_classification.csv | head -n1）
> echo $ BLAST_OUT >> 11_blast.log
> 
> 命令退出状态：
> 2
> 
> 命令输出：（
> 空）
> 
> 命令错误：
> BLAST数据库错误：在搜索路径[/ media / kraken / NanoCLUST / work / ff / 483a7d41cb9ec59d392dda702d6293 :: / home中，找不到核苷酸数据库[/ home / ubuntu / bin / NanoCLUST / db / 16S_ribosomal_RNA]的别名或索引文件/ ubuntu / bin / NanoCLUST / db / taxdb：]
> 
> 工作目录：
> / media / kraken / NanoCLUST / work / ff / 483a7d41cb9ec59d392dda702d6293
> 
> 提示：解决问题后，可以继续执行，将选项添加`-resume`到运行命令行

  you  can  use  ”docke“

**Comment by HaiyangDu** [comment]
> 你好，
> 
> 我已经按照说明下载了所需的数据库，但是此问题仍然存在：
> 
> 命令执行：
> 
> 导出BLASTDB =
> 导出BLASTDB = $ BLASTDB：/ home / ubuntu / bin / NanoCLUST / db / taxdb blastn-
> 查询共识。fasta-db / home / ubuntu / bin / NanoCLUST / db / 16S_ribosomal_RNA -task blastn -dust no -outfmt“ 10个sscinames staxids evalue长度pident“ -evalue 11 -max_hsps 50 -max_target_seqs 5 | sed's /，/; / g'>共识
> _分类.csv #DECIDE最终分类
> cat 11_draft.log> 11_blast.log
> echo -n“;” >> 11_blast.log
> BLAST_OUT = $（cut -d“;” -f1,2,4,5confidence_classification.csv | head -n1）
> echo $ BLAST_OUT >> 11_blast.log
> 
> 命令退出状态：
> 2
> 
> 命令输出：（
> 空）
> 
> 命令错误：
> BLAST数据库错误：在搜索路径[/ media / kraken / NanoCLUST / work / ff / 483a7d41cb9ec59d392dda702d6293 :: / home中，找不到核苷酸数据库[/ home / ubuntu / bin / NanoCLUST / db / 16S_ribosomal_RNA]的别名或索引文件/ ubuntu / bin / NanoCLUST / db / taxdb：]
> 
> 工作目录：
> / media / kraken / NanoCLUST / work / ff / 483a7d41cb9ec59d392dda702d6293
> 
> 提示：解决问题后，可以继续执行，将选项添加`-resume`到运行命令行

you  can  try  the  ” docter“

**Comment by genomicsITER** [comment]
Hi. I've updated NanoCLUST. The behaviour of --db and --taxdb parameter has changed.

Now it is assumed that databases are downloaded inside the NanoCLUST dir and they MUST be specified as a relative path (--db "db/16S_ribosomal_RNA" --db "db/taxdb") in the 'nextflow run' command.

fahadkhokhar, This time I'm using the prefix $baseDir instead o giving the full path. I hope this time the db can be found inside the container.

**Comment by fahadkhokhar** [comment]
Hello, unfortunately still not working. I have tried various options for the --db and --tax entries.

My previous post of the error had an empty path as part of the command executed:

export BLASTDB=
export BLASTDB=$BLASTDB:/home/ubuntu/bin/NanoCLUST/db/taxdb

**Comment by genomicsITER** [comment]
I'm checking if there is a problem with the docker container.

Also, does the db directory contains the following structure?
 ls db/
16S_ribosomal_RNA.ndb,
16S_ribosomal_RNA.nnd
16S_ribosomal_RNA.nos
16S_ribosomal_RNA.ntf
taxdb.btd
16S_ribosomal_RNA.nhr
16S_ribosomal_RNA.nni
16S_ribosomal_RNA.not
16S_ribosomal_RNA.nto
taxdb.bti
16S_ribosomal_RNA.nin
16S_ribosomal_RNA.nog
16S_ribosomal_RNA.nsq
taxdb

ls db/taxdb
taxdb.btd 
taxdb.bti

**Comment by fahadkhokhar** [comment]
Yes that is the exact structure I have

**Comment by DavidFY-Hub** [comment]
> Yes that is the exact structure I have

hi，my  db is in NanoCLUST,so

####
nextflow run  NanoCLUST/main.nf   \
   --reads 'no/*.fastq'  -profile docker   \
  --db  db/16S_ribosomal_RNA    
  --tax db/taxdb/  
......
##
like  this   is ok

**Comment by genomicsITER** [comment]
I made it to replicate an error like yours. I solved it mounting the database separatedly in the consensus_classification process. These changes are included in the last commit.

**Comment by fahadkhokhar** [comment]
Success! Ran to completion for a single sample - now to run on all 34 :)

Many thanks for resolving this issue!

**Comment by genomicsITER** [comment]
Thank you for your time. Glad you finally ran the pipeline at 100%.

Feel free to open a new issue if you find any problem analyzing your data.
