### ISSUE TITLE
Error consensus classification

### ISSUE THREAD

**Issue by SchNadine** [genomicsITER/NanoCLUST#35]
Hey!

For our project we need to make our own pipeline for 16S Nanopore data and comparing it with an existing pipeline. The data is trimmed with Porechop. We are using NanoCLUST to compare output. We are experiencing still the same issue with NanoCLUST namely with classifying the consensus of our reads.

**_The following command is used in shell:_**

nextflow run nanoclust/NanoCLUST/main.nf -profile docker --reads test_data/testdata_bc01_115000reads.fastq --db nanoclust/NanoCLUST/db/16S_ribosomal_RNA --tax nanoclust/NanoCLUST/db/taxdb

**_The following error is occuring:_**

Error executing process > 'consensus_classification (1)'

Caused by:
  Process `consensus_classification (1)` terminated with an error exit status (2)

Command executed:

  export BLASTDB=
  export BLASTDB=$BLASTDB:/tmp/nanoclust/NanoCLUST/db/taxdb
  blastn -query consensus.fasta -db /tmp/nanoclust/NanoCLUST/db/16S_ribosomal_RNA -task blastn -dust no -outfmt "10 sscinames staxids evalue length pident" -evalue 11 -max_hsps 50 -max_target_seqs 5 | sed 's/,/;/g' > consensus_classification.csv
  #DECIDE FINAL CLASSIFFICATION
  cat 33_draft.log > 33_blast.log
  echo -n ";" >> 33_blast.log
  BLAST_OUT=$(cut -d";" -f1,2,4,5 consensus_classification.csv | head -n1)
  echo $BLAST_OUT >> 33_blast.log

Command exit status:
  2

Command output:
  (empty)

Command error:
  BLAST Database error: No alias or index file found for nucleotide database [/tmp/nanoclust/NanoCLUST/db/16S_ribosomal_RNA] in search path [/mnt/StudentFiles/2020-21/Project11/project/work/64/555f24ca05d9c9f4c0807c78fb671c::/tmp/nanoclust/NanoCLUST/db/taxdb:]

Work dir:
  /mnt/StudentFiles/2020-21/Project11/project/work/64/555f24ca05d9c9f4c0807c78fb671c

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

We already read a [closed issue](https://github.com/genomicsITER/NanoCLUST/issues/3) which had the same issue as we have, but we still do not understand where the issue lies and how to solve the issue.

Thank you in advance!

Kind Regards,

Nadine

**Comment by hkunerth** [comment]
> See this problem here:
> 
> https://githubhot.com/repo/genomicsITER/NanoCLUST/issues/43?page=1

This link appears to be dead. I am having the same issue reported here: is there any chance that a working link to a solution exists?

**Comment by thierryjanssens** [comment]
Use absolute paths to the databases (in NanoCLUST/db).
