### ISSUE TITLE
Link to nf-core slack

### ISSUE THREAD

**Issue by ewels** [genomicsITER/NanoCLUST#5]
Hi there,

Congratulations on the new pipeline and preprint - it looks great!

It seems that you used the @nf-core pipeline template to make the workflow. Absolutely no problem with this at all (in fact it's encouraged!), however it looks like the readme still has the following at the bottom:

> For further information or help, don't hesitate to get in touch on [Slack](https://nfcore.slack.com/channels/nf-core/nanoclust) (you can join with [this invite](https://nf-co.re/join/slack)).

I think this is causing some confusion - we've had a couple of people asking for help with the pipeline on the nf-core slack over the past days, presumably finding it because of the above links.

If it's ok, would you mind removing the above text to avoid the confusion? Of course if you're interested in bringing the pipeline into the @nf-core community then we would be more than happy to discuss that too!

Thanks,

Phil

**Comment by genomicsITER** [comment]
Hi Phil,

Thank you very much for your time. The nf-core guidelines and template were really useful and we are going to work with them again in the future. I apologize for this mistake, I understand that this could be annoying. The readme will be modified right now.

Our plan was to bring nanoclust to the nf-core community. We released the tool a few weeks ago and we are still testing it for the different use cases and conditions. We will be glad to have our pipeline in the community and I will contact you once we feel the pipeline is ready to vast majority of users

Thanks

**Comment by ewels** [comment]
Great - thanks for the speedy response!

Feel free to join the nf-core Slack yourselves at any point, we would be happy to help / discuss however we can. There are a few nanopore pipelines being developed currently so it could be good to have you around!
