### ISSUE TITLE
Missing workflow definition - DSL2 requires at least a workflow block in the main script

### ISSUE THREAD

**Issue by timyaro** [genomicsITER/NanoCLUST#63]
Hello,

When I run the test script:

nextflow run main.nf -profile test,docker

I get the following error message:

Missing workflow definition - DSL2 requires at least a workflow block in the main script.

How do I go about fixing this?

Also, just a heads up, I am very new with bioinformatics!

**Comment by niederro** [comment]
Hey @timyaro ,

It is because you use a new version of Nextflow. When starting the shell use: export NXF_DEFAULT_DSL=1 

Then it should work

**Comment by timyaro** [comment]
@niederro It worked! I greatly appreciate your help!
