### ISSUE TITLE
kmer_freq error

### ISSUE THREAD

**Issue by YulinzhangSia** [genomicsITER/NanoCLUST#8]
![image](https://user-images.githubusercontent.com/51396070/87140343-f86cf680-c2d3-11ea-8b31-4673668a4414.png)

Dear NanoCLUST team, the system reported an error when I analysis my data. Do you have any advice or suggestion?
Thanks a lot!

**Comment by genomicsITER** [comment]
Hi

Thank you for contacting us. Could you provide the complete log or the "command output" that appears in your log error?
If you have Docker installed, we recommend to try the docker profile to avoid errors related to conda environments.

**Comment by genomicsITER** [comment]
Error fixed in #12
