### ISSUE TITLE
How about metagenomics data using NanoCLUST workflow

### ISSUE THREAD

**Issue by ray1919** [genomicsITER/NanoCLUST#9]
If I replace 16s db with bac+fungi+virus genome db, will this workflow appliable to metagenomics Nanopore data?

**Comment by genomicsITER** [comment]
Hi,

Thank you for contacting us. That is a very interesting question. We would like to test NanoCLUST with shotgun metagenomics soon once we finish with some updates and performance improvements. The parameters are tuned for 1400bp-1600bp reads so changes in the process scripts are needed. This UMAP-HDBSCAN method has been applied in Nanopore metagenomics data by Beaulaurier et al. DOI: 10.1101/619684
